
name: 'Terraform Validate'

on:
  push:
    branches-ignore:
      - main
    paths:
      - devops/envs/prod-unicc/*

permissions:
  contents: read
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops/envs/prod-unicc/

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Step up Terraform
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        sed -i "s|git@bitbucket.org:awsopda/who-|https://github.com/finddx/|" ./*
        rm -f backend.tf
        terraform init -input=false
      
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
